fields:
  - name: label
    caption: Topology
    type: displayfield
  - name: topo
    type: radio-fieldset
    values:
        - value: 0-dev
          caption: '<b>Development:</b> one master (1) and one scalable worker (1+)'
        - value: 1-prod
          caption: '<b>Production:</b> multi master (3) with API balancers (2+) and scalable workers (2+)'
    default: 0-dev

  - type: displayfield
    cls: warning
    height: 30
    hideLabel: true
    hidden: true
    markup:

  - name: dashboard
    type: list
    caption: Kubernetes Dashboard
    values:
      version1: Kubernetes Dashboard v1 (Stable)
      version2: Kubernetes Dashboard v2 (RC)
    default: version2
    hideLabel: false
    editable: false

  - type: checkbox
    name: storage
    caption: Attach dedicated NFS Storage with dynamic volume provisioning
    value: true

  - type: checkbox
    name: api
    caption: Enable Remote API Access
    value: false

  - type: string
    name: version
    inputType: hidden
    caption: Kubernetes Version
    default: v1.15.3